repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: debug-statements
    -   id: etect-private-key
    -   id: check-json
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: name-tests-test
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        #args: [--show-error-codes, --warn-unused-configs, --disallow-untyped-calls, --disallow-untyped-defs, --disallow-incomplete-defs, --check-untyped-defs, --python-version=3.11]
        #additional_dependencies:
        #  - requests
        #  - types-requests
        #  - types-cachetools
        #  - alembic
        exclude: |
          (?x)(
            ^tests.*|
          )